name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env
        run: echo "TAG=$(echo $(date +%Y.%m.%d))" >> $GITHUB_ENV

      - name: Docker Login
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ github.event_name == 'push' && 'sholdee/caddy-proxy-cloudflare:latest' || '' }}
            ${{ github.event_name == 'push' && 'sholdee/caddy-proxy-cloudflare:${{ env.TAG }}' || '' }}

      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' }}
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ env.TAG }}
          allowUpdates: true
          makeLatest: true
